#!/usr/bin/env python3
"""Calibration stats — surfaces estimate-vs-actual data for orch task time-budgeting.

Reads orch_task_calibrations and prints:
- Overall mean / p50 / p90 of estimate_multiplier (actual / estimated)
- Breakdown by task_type
- Breakdown by complexity
- Breakdown by completion_status
- Top 5 worst-overestimated tasks (highest multiplier means BMO budgeted way more than needed)
- Most-recent-7 trend

Optional: --markdown writes a doc-friendly summary to stdout (or path).
"""

import argparse
import os
import sqlite3
import statistics
import sys
from collections import defaultdict
from pathlib import Path

DB_PATH = os.path.expanduser("~/Library/Application Support/kithkit/kithkit.db")

def percentile(xs: list[float], p: float) -> float:
    if not xs:
        return 0.0
    s = sorted(xs)
    k = (len(s) - 1) * p
    f = int(k)
    c = min(f + 1, len(s) - 1)
    return s[f] + (s[c] - s[f]) * (k - f)

def fmt(n: float) -> str:
    return f"{n:.2f}"

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--markdown", action="store_true", help="Emit markdown for doc embed")
    ap.add_argument("--out", default=None, help="Write to this file instead of stdout")
    args = ap.parse_args()

    if not Path(DB_PATH).exists():
        sys.exit(f"DB not found: {DB_PATH}")

    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    cur = conn.cursor()
    cur.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='orch_task_calibrations'")
    if not cur.fetchone():
        sys.exit("orch_task_calibrations table missing — run scripts/migrations/calibration-log.sql first")

    cur.execute("""SELECT orch_task_id, escalated_at, estimated_minutes, actual_minutes, task_type,
                          complexity, completion_status, estimate_multiplier, notes
                     FROM orch_task_calibrations""")
    rows = cur.fetchall()

    total = len(rows)
    with_mult = [r for r in rows if r["estimate_multiplier"] is not None]
    multipliers = [r["estimate_multiplier"] for r in with_mult]

    out = []
    def p(s=""): out.append(s)

    if args.markdown:
        p("# Calibration Baseline — generated by scripts/calibration/stats.py")
        p()
        p(f"**Total rows:** {total} · **with estimate present:** {len(with_mult)}")
        p()
    else:
        p(f"=== Calibration stats (n={total}, with-estimate={len(with_mult)}) ===\n")

    # Overall
    if multipliers:
        mean = statistics.mean(multipliers)
        p50 = percentile(multipliers, 0.50)
        p90 = percentile(multipliers, 0.90)
        if args.markdown:
            p("## Overall")
            p(f"- mean multiplier: **{fmt(mean)}x**")
            p(f"- p50:             **{fmt(p50)}x**")
            p(f"- p90:             **{fmt(p90)}x**")
            p()
        else:
            p(f"OVERALL multiplier: mean={fmt(mean)} p50={fmt(p50)} p90={fmt(p90)}")
            p()

    # By task_type
    by_type = defaultdict(list)
    for r in with_mult:
        by_type[r["task_type"]].append(r["estimate_multiplier"])
    if args.markdown:
        p("## By task_type")
        p("| type | n | mean | p50 |")
        p("|---|---:|---:|---:|")
        for t, xs in sorted(by_type.items(), key=lambda x: -len(x[1])):
            p(f"| {t} | {len(xs)} | {fmt(statistics.mean(xs))}x | {fmt(percentile(xs, 0.5))}x |")
        p()
    else:
        p("BY task_type:")
        for t, xs in sorted(by_type.items(), key=lambda x: -len(x[1])):
            p(f"  {t:12s} n={len(xs):3d}  mean={fmt(statistics.mean(xs))}  p50={fmt(percentile(xs, 0.5))}")
        p()

    # By complexity
    by_cplx = defaultdict(list)
    for r in with_mult:
        by_cplx[r["complexity"]].append(r["estimate_multiplier"])
    if args.markdown:
        p("## By complexity")
        p("| cplx | n | mean | p50 |")
        p("|---|---:|---:|---:|")
        for c in ("S", "M", "L", "XL"):
            xs = by_cplx.get(c, [])
            if not xs: continue
            p(f"| {c} | {len(xs)} | {fmt(statistics.mean(xs))}x | {fmt(percentile(xs, 0.5))}x |")
        p()
    else:
        p("BY complexity:")
        for c in ("S", "M", "L", "XL"):
            xs = by_cplx.get(c, [])
            if not xs: continue
            p(f"  {c:3s} n={len(xs):3d}  mean={fmt(statistics.mean(xs))}  p50={fmt(percentile(xs, 0.5))}")
        p()

    # By completion_status
    by_status = defaultdict(list)
    for r in with_mult:
        by_status[r["completion_status"] or "unknown"].append(r["estimate_multiplier"])
    if args.markdown:
        p("## By completion_status")
        p("| status | n | mean |")
        p("|---|---:|---:|")
        for s, xs in sorted(by_status.items(), key=lambda x: -len(x[1])):
            p(f"| {s} | {len(xs)} | {fmt(statistics.mean(xs))}x |")
        p()
    else:
        p("BY completion_status:")
        for s, xs in sorted(by_status.items(), key=lambda x: -len(x[1])):
            p(f"  {s:12s} n={len(xs):3d}  mean={fmt(statistics.mean(xs))}")
        p()

    # Top overestimates
    sorted_rows = sorted(with_mult, key=lambda r: -(r["estimate_multiplier"] or 0))
    if args.markdown:
        p("## Top 5 over-estimates (actual << estimated)")
        p("| label | est_min | actual_min | mult |")
        p("|---|---:|---:|---:|")
        for r in sorted_rows[:5]:
            label = r["notes"] or r["orch_task_id"] or "(unlabeled)"
            label = label[:60]
            p(f"| {label} | {r['estimated_minutes']} | {r['actual_minutes']} | {fmt(r['estimate_multiplier'])}x |")
        p()
    else:
        p("TOP 5 over-estimates (actual << estimated):")
        for r in sorted_rows[:5]:
            label = (r["notes"] or r["orch_task_id"] or "(unlabeled)")[:60]
            p(f"  {fmt(r['estimate_multiplier']):>6}x  est={r['estimated_minutes']:4d}m  act={r['actual_minutes']:4d}m  {label}")
        p()

    # Most recent 7
    cur.execute("""SELECT escalated_at, estimated_minutes, actual_minutes, estimate_multiplier, task_type, notes
                     FROM orch_task_calibrations
                    WHERE estimate_multiplier IS NOT NULL
                 ORDER BY escalated_at DESC LIMIT 7""")
    recent = cur.fetchall()
    if args.markdown:
        p("## Most recent 7 (with estimate)")
        p("| escalated_at | type | est | act | mult |")
        p("|---|---|---:|---:|---:|")
        for r in recent:
            p(f"| {(r['escalated_at'] or '')[:16]} | {r['task_type']} | {r['estimated_minutes']}m | {r['actual_minutes']}m | {fmt(r['estimate_multiplier'])}x |")
        p()
    else:
        p("MOST RECENT 7 (with estimate):")
        for r in recent:
            p(f"  {(r['escalated_at'] or '')[:16]}  {r['task_type']:10s}  est={r['estimated_minutes']}m  act={r['actual_minutes']}m  mult={fmt(r['estimate_multiplier'])}")
        p()

    # Calibrated estimate cheat-sheet
    # multiplier = actual / estimated. If you over-estimated by 5x, multiplier=0.20.
    # So the *adjustment* you should apply to your gut estimate IS the multiplier.
    # Example: gut said 100m, mean multiplier for this type is 0.14 → ship 14m.
    if args.markdown:
        p("## Calibrated estimate cheat-sheet")
        p("Multiply your gut estimate by this factor and you'll be closer to actual:")
        p()
        p("| task_type | adjustment | i.e. gut 60m → ship |")
        p("|---|---:|---:|")
        for t, xs in sorted(by_type.items(), key=lambda x: -len(x[1])):
            adj = statistics.mean(xs)
            p(f"| {t} | {fmt(adj)}x | {int(round(60 * adj))}m |")
        p()
        p("Read: if your gut says `X` minutes, ship `X × adjustment` instead. Adjustment < 1 means you over-estimated; the smaller it is, the worse the over-estimate was.")
    else:
        p("CALIBRATED CHEAT-SHEET (gut * this = honest):")
        for t, xs in sorted(by_type.items(), key=lambda x: -len(x[1])):
            adj = statistics.mean(xs)
            p(f"  {t:12s} adj={fmt(adj)}x   (gut 60m -> {int(round(60*adj))}m)")

    body = "\n".join(out)
    if args.out:
        Path(args.out).write_text(body + "\n")
        print(f"Wrote {args.out}")
    else:
        print(body)

    conn.close()

if __name__ == "__main__":
    main()
