/**
 * Tmux session management — spawn, inject messages, teardown.
 *
 * Handles orchestrator and comms agent tmux sessions.
 * The daemon uses this to:
 * - Inject messages into persistent agent sessions (comms/orchestrator)
 * - Spawn on-demand orchestrator sessions
 * - Tear down orchestrator sessions when work is done
 */

import { execFileSync, execFile } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { createLogger } from '../core/logger.js';
import { estTimestamp } from '../core/session-bridge.js';

const log = createLogger('tmux');

// ── Config ──────────────────────────────────────────────────

const TMUX_BIN = '/opt/homebrew/bin/tmux';
const TMUX_SOCKET = `/private/tmp/tmux-${process.getuid?.() ?? 501}/default`;

const COMMS_SESSION = 'commsagent';
const ORCH_SESSION = 'orchagent';

let projectDir = process.cwd();

export function configure(opts: { projectDir: string }): void {
  projectDir = opts.projectDir;
}

// ── Session name mapping ────────────────────────────────────

function resolveSession(agentId: string): string | null {
  if (agentId === 'comms') return COMMS_SESSION;
  if (agentId === 'orchestrator') return ORCH_SESSION;
  return null; // Workers don't have tmux sessions
}

// ── Message injection ───────────────────────────────────────

/**
 * Inject text into a tmux session via send-keys.
 * Returns true if injection succeeded, false if session doesn't exist.
 */
export function injectMessage(agentId: string, text: string): boolean {
  const session = resolveSession(agentId);
  if (!session) return false;

  try {
    // Check if session exists first
    execFileSync(TMUX_BIN, ['-S', TMUX_SOCKET, 'has-session', '-t', `=${session}`], {
      timeout: 5000,
    });
  } catch {
    log.warn('Tmux session not found for message injection', { agentId, session });
    return false;
  }

  try {
    // Prepend EST timestamp and send as keystrokes, then press Enter
    const stamped = `${estTimestamp()} ${text}`;
    execFileSync(TMUX_BIN, ['-S', TMUX_SOCKET, 'send-keys', '-t', `${session}:`, '-l', stamped], {
      timeout: 5000,
    });
    // Small delay to let tmux buffer the text before submitting
    execFileSync('/bin/sleep', ['0.15'], { timeout: 2000 });
    execFileSync(TMUX_BIN, ['-S', TMUX_SOCKET, 'send-keys', '-t', `${session}:`, 'Enter'], {
      timeout: 5000,
    });
    log.info('Message injected into tmux session', { agentId, session, length: text.length });
    return true;
  } catch (err) {
    log.error('Failed to inject message into tmux', {
      agentId,
      session,
      error: err instanceof Error ? err.message : String(err),
    });
    return false;
  }
}

// ── Orchestrator session lifecycle ──────────────────────────

// How long the wrapper waits for a new task before exiting (ms)
const ORCHESTRATOR_IDLE_WAIT_MS = 2 * 60 * 1000; // 2 minutes
// How often to poll for new tasks while idle (ms)
const ORCHESTRATOR_POLL_INTERVAL_MS = 10 * 1000; // 10 seconds

/**
 * Build the inline bash wrapper script that runs Claude in a loop:
 *  1. Runs Claude with -p <prompt>
 *  2. After Claude exits, polls the daemon for new task messages
 *  3. If a task arrives, runs Claude again with the task body
 *  4. If no task within IDLE_WAIT seconds, exits and marks status stopped
 *
 * The script is self-contained — no external files needed.
 */
export function buildOrchestratorWrapperScript(
  claudeBin: string,
  initialPrompt: string,
  daemonPort: number = 3847,
): string {
  // Encode the initial prompt as base64 so it can be safely embedded in the
  // script without any shell quoting or heredoc delimiter concerns.
  const promptB64 = Buffer.from(initialPrompt, 'utf8').toString('base64');
  const idleWaitSec = Math.floor(ORCHESTRATOR_IDLE_WAIT_MS / 1000);
  const pollIntervalSec = Math.floor(ORCHESTRATOR_POLL_INTERVAL_MS / 1000);

  return `#!/usr/bin/env bash
# Kithkit orchestrator wrapper — keeps session alive between tasks.
# DO NOT edit manually — generated by daemon/src/agents/tmux.ts

CLAUDE_BIN=${JSON.stringify(claudeBin)}
DAEMON_PORT=${daemonPort}
IDLE_WAIT_SEC=${idleWaitSec}
POLL_INTERVAL_SEC=${pollIntervalSec}
PROMPT_FILE=$(mktemp /tmp/orch-prompt-XXXXXX)

# Validate dependencies
if ! command -v python3 >/dev/null 2>&1; then
  echo "ERROR: python3 not found — required for JSON parsing in orchestrator wrapper" >&2
  exit 1
fi

# Decode the base64-encoded initial prompt into the temp file
printf '%s' '${promptB64}' | base64 -d > "$PROMPT_FILE"

# On exit: clean up temp file and mark orchestrator stopped in daemon DB
cleanup() {
  rm -f "$PROMPT_FILE"
  curl -s -o /dev/null -X PUT "http://localhost:$DAEMON_PORT/api/agents/orchestrator" \\
    -H "Content-Type: application/json" \\
    -d '{"status":"stopped"}' || true
}
trap cleanup EXIT

run_claude() {
  local pf="$1"
  "$CLAUDE_BIN" --dangerously-skip-permissions -p "$(cat "$pf")"
}

# ── Seed LAST_MSG_ID from current max message ID ─────────────
# We track the highest message ID we've seen so we can poll for messages
# with id > LAST_MSG_ID. This avoids a race where the orchestrator Claude
# process reads and marks messages as read via the API before this wrapper's
# polling loop runs — ?since_id is immune to read_at / processed_at state.
LAST_MSG_ID=$(curl -s -f "http://localhost:$DAEMON_PORT/api/messages?agent=orchestrator&since_id=0" 2>/dev/null \\
  | python3 -c "
import sys, json
d = json.load(sys.stdin)
msgs = d.get('data', [])
if msgs:
    print(max(m.get('id', 0) for m in msgs))
else:
    print(0)
" 2>/dev/null || printf '0')

# ── Run initial task ─────────────────────────────────────────
run_claude "$PROMPT_FILE"

# ── Poll for follow-up tasks ─────────────────────────────────
elapsed=0
while [ "$elapsed" -lt "$IDLE_WAIT_SEC" ]; do
  sleep "$POLL_INTERVAL_SEC"
  elapsed=$((elapsed + POLL_INTERVAL_SEC))

  # Check for new task messages addressed to orchestrator with id > LAST_MSG_ID.
  # Using since_id avoids the race where Claude (running as the orchestrator) reads
  # messages via the API and marks them read before this wrapper's loop runs.
  RESPONSE=$(curl -s -f "http://localhost:$DAEMON_PORT/api/messages?agent=orchestrator&since_id=$LAST_MSG_ID&type=task" 2>/dev/null || printf '{"data":[]}')
  COUNT=$(printf '%s' "$RESPONSE" | python3 -c "import sys,json; d=json.load(sys.stdin); print(len(d.get('data',[])))" 2>/dev/null || printf '0')

  if [ "$COUNT" -gt "0" ]; then
    # Extract and decode the task from the first new message body.
    # Message body is JSON: {"task":"...", "context":"..."}
    # Also capture the max message ID so we don't re-process this message.
    PARSED=$(printf '%s' "$RESPONSE" | python3 -c "
import sys, json
d = json.load(sys.stdin)
msgs = d.get('data', [])
if msgs:
    msg = msgs[0]
    new_last_id = max(m.get('id', 0) for m in msgs)
    raw = msg.get('body', '')
    try:
        parsed = json.loads(raw)
        out = parsed.get('task', raw)
    except Exception:
        out = raw
    # Output: first line = new LAST_MSG_ID, rest = task body
    print(new_last_id)
    sys.stdout.write(out)
" 2>/dev/null || printf '')

    if [ -n "$PARSED" ]; then
      # First line is the new LAST_MSG_ID
      NEW_LAST_ID=$(printf '%s' "$PARSED" | head -1)
      TASK=$(printf '%s' "$PARSED" | tail -n +2)

      if [ -n "$TASK" ]; then
        # Advance our cursor so we never re-process this batch
        LAST_MSG_ID="$NEW_LAST_ID"
        # Write task to prompt file and run Claude
        printf '%s' "$TASK" > "$PROMPT_FILE"
        run_claude "$PROMPT_FILE"
        # Reset idle timer so we wait the full window for the next task
        elapsed=0
      fi
    fi
  fi
done

# Idle window exhausted — exit cleanly (cleanup trap marks status stopped)
exit 0
`;
}

/**
 * Spawn an orchestrator tmux session running Claude Code.
 * Returns the session name, or null if spawn failed.
 *
 * The session runs a wrapper script that keeps the shell alive between tasks,
 * polling for new work for up to 2 minutes before exiting cleanly.
 */
export function spawnOrchestratorSession(prompt: string): string | null {
  const session = resolveSession('orchestrator')!;

  // Check if already running
  try {
    execFileSync(TMUX_BIN, ['-S', TMUX_SOCKET, 'has-session', '-t', `=${session}`], {
      timeout: 5000,
    });
    log.warn('Orchestrator session already exists', { session });
    // Session exists — inject the new task prompt
    injectMessage('orchestrator', prompt);
    return session;
  } catch {
    // Session doesn't exist — good, we'll create it
  }

  try {
    const claudeBin = `${process.env.HOME}/.local/bin/claude`;
    const wrapperScript = buildOrchestratorWrapperScript(claudeBin, prompt);

    // Write wrapper script to a temp file so tmux can execute it
    const scriptPath = `/tmp/kithkit-orch-${Date.now()}.sh`;
    writeFileSync(scriptPath, wrapperScript, { mode: 0o700 });

    // Create a new detached tmux session running the wrapper script
    execFileSync(TMUX_BIN, [
      '-S', TMUX_SOCKET,
      'new-session',
      '-d',             // detached
      '-s', session,    // session name
      '-c', projectDir, // working directory
      '-x', '200',      // width
      '-y', '50',       // height
      '/bin/bash', scriptPath,
    ], {
      timeout: 10000,
      env: {
        ...process.env,
        PATH: `${process.env.HOME}/.local/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin`,
        CLAUDECODE: '',  // Clear nesting guard — orchestrator is a separate session
      },
    });

    log.info('Orchestrator session spawned with wrapper', { session, projectDir });
    return session;
  } catch (err) {
    log.error('Failed to spawn orchestrator session', {
      session,
      error: err instanceof Error ? err.message : String(err),
    });
    return null;
  }
}

/**
 * Kill the orchestrator tmux session.
 * Returns true if killed, false if session didn't exist.
 */
export function killOrchestratorSession(): boolean {
  const session = resolveSession('orchestrator')!;

  try {
    execFileSync(TMUX_BIN, ['-S', TMUX_SOCKET, 'kill-session', '-t', `=${session}`], {
      timeout: 5000,
    });
    log.info('Orchestrator session killed', { session });
    return true;
  } catch {
    log.warn('Orchestrator session not found for kill', { session });
    return false;
  }
}

/**
 * Check if the orchestrator session exists (alive = session running).
 * This returns true even when the wrapper is idle-waiting between tasks.
 */
export function isOrchestratorAlive(): boolean {
  const session = resolveSession('orchestrator')!;

  try {
    execFileSync(TMUX_BIN, ['-S', TMUX_SOCKET, 'has-session', '-t', `=${session}`], {
      timeout: 5000,
    });
    return true;
  } catch {
    return false;
  }
}

/**
 * Check if the orchestrator is actively running Claude (not just idle-waiting).
 *
 * The wrapper script runs Claude as a child of bash, so tmux's
 * pane_current_command always reports "bash". Instead, we grab the wrapper's
 * PID (#{pane_pid}) and use pgrep to check whether any "claude" process is a
 * descendant of that PID.
 *
 * Returns:
 *  - 'active'  — session exists and a claude process is running under the wrapper
 *  - 'waiting' — session exists but no claude child (idle polling loop)
 *  - 'dead'    — no session
 */
export function getOrchestratorState(): 'active' | 'waiting' | 'dead' {
  const session = resolveSession('orchestrator')!;

  try {
    execFileSync(TMUX_BIN, ['-S', TMUX_SOCKET, 'has-session', '-t', `=${session}`], {
      timeout: 5000,
    });
  } catch {
    return 'dead';
  }

  try {
    // Get the PID of the wrapper bash process that owns the tmux pane
    const panePid = execFileSync(TMUX_BIN, [
      '-S', TMUX_SOCKET,
      'display-message',
      '-t', `${session}:`,
      '-p', '#{pane_pid}',
    ], { timeout: 5000, encoding: 'utf8' }).trim();

    if (!panePid || !/^\d+$/.test(panePid)) {
      return 'waiting';
    }

    // Check if any "claude" process is a descendant of the wrapper PID
    try {
      execFileSync('/usr/bin/pgrep', ['-P', panePid, '-f', 'claude'], {
        timeout: 5000,
      });
      // pgrep exits 0 → at least one claude descendant found
      return 'active';
    } catch {
      // pgrep exits non-zero → no matching descendants
      return 'waiting';
    }
  } catch (err) {
    log.warn('getOrchestratorState: failed to determine process tree, assuming waiting', {
      error: err instanceof Error ? err.message : String(err),
    });
    return 'waiting';
  }
}

/**
 * List all tmux sessions managed by the daemon.
 */
export function listSessions(): string[] {
  try {
    const output = execFileSync(TMUX_BIN, [
      '-S', TMUX_SOCKET,
      'list-sessions',
      '-F', '#{session_name}',
    ], { timeout: 5000 }).toString().trim();
    return output ? output.split('\n') : [];
  } catch {
    return [];
  }
}

// ── Testing ─────────────────────────────────────────────────

export function _getCommsSession(): string { return COMMS_SESSION; }
export function _getOrchestratorSession(): string { return ORCH_SESSION; }
