/**
 * Tmux session management — spawn, inject messages, teardown.
 *
 * Handles orchestrator and comms agent tmux sessions.
 * The daemon uses this to:
 * - Inject messages into persistent agent sessions (comms/orchestrator)
 * - Spawn on-demand orchestrator sessions
 * - Tear down orchestrator sessions when work is done
 */

import { execFileSync, execFile } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { createLogger } from '../core/logger.js';
import { estTimestamp } from '../core/session-bridge.js';

const log = createLogger('tmux');

// ── Config ──────────────────────────────────────────────────

export const TMUX_BIN = '/opt/homebrew/bin/tmux';
export const TMUX_SOCKET = `/private/tmp/tmux-${process.getuid?.() ?? 501}/default`;

const COMMS_SESSION = 'comms1';
const ORCH_SESSION = 'orch1';

let projectDir = process.cwd();

export function configure(opts: { projectDir: string }): void {
  projectDir = opts.projectDir;
}

// ── Session name mapping ────────────────────────────────────

export function resolveSession(agentId: string): string | null {
  if (agentId === 'comms') return COMMS_SESSION;
  if (agentId === 'orchestrator') return ORCH_SESSION;
  return null; // Workers don't have tmux sessions
}

// ── Message injection ───────────────────────────────────────

/**
 * Inject text into a tmux session via send-keys.
 * Returns true if injection succeeded, false if session doesn't exist.
 */
export function injectMessage(agentId: string, text: string): boolean {
  const session = resolveSession(agentId);
  if (!session) {
    log.warn('No tmux session mapping for agent', { agentId });
    return false;
  }

  try {
    // Check if session exists first
    execFileSync(TMUX_BIN, ['-S', TMUX_SOCKET, 'has-session', '-t', `=${session}`], {
      timeout: 5000,
    });
  } catch {
    log.warn('Tmux session not found for message injection', { agentId, session });
    return false;
  }

  try {
    // Prepend EST timestamp and send as keystrokes, then press Enter
    const stamped = `${estTimestamp()} ${text}`;
    execFileSync(TMUX_BIN, ['-S', TMUX_SOCKET, 'send-keys', '-t', `${session}:`, '-l', stamped], {
      timeout: 5000,
    });
    // Small delay to let tmux buffer the text before submitting
    execFileSync('/bin/sleep', ['0.15'], { timeout: 2000 });
    execFileSync(TMUX_BIN, ['-S', TMUX_SOCKET, 'send-keys', '-t', `${session}:`, 'Enter'], {
      timeout: 5000,
    });
    log.info('Message injected into tmux session', { agentId, session, length: text.length });
    return true;
  } catch (err) {
    log.error('Failed to inject message into tmux', {
      agentId,
      session,
      error: err instanceof Error ? err.message : String(err),
    });
    return false;
  }
}

// ── Orchestrator session lifecycle ──────────────────────────

/**
 * Build the bash restart loop script that runs Claude in a persistent loop.
 *
 * The orchestrator uses `--profile orchestrator` which loads the SOP skill file.
 * On each start, Claude checks its task queue from the database and works through
 * pending tasks. When Claude exits, the loop decides whether to restart:
 *  1. /tmp/orch-exit-requested — daemon signals clean shutdown → exit
 *  2. .claude/state/orch-restart-requested — orch hit context limit → restart
 *  3. Task table query — restart only if pending/in_progress tasks remain
 */
function buildOrchestratorRestartLoop(): string {
  return `#!/bin/bash
# Kithkit orchestrator restart loop — generated by daemon/src/agents/tmux.ts
set -euo pipefail
DAEMON_PORT=\${DAEMON_PORT:-3847}
CLAUDE_BIN="$HOME/.local/bin/claude"

# On exit: mark orchestrator stopped
cleanup() {
  curl -s -o /dev/null -X PUT "http://localhost:\$DAEMON_PORT/api/agents/orchestrator" \\
    -H "Content-Type: application/json" \\
    -d '{"status":"stopped"}' || true
}
trap cleanup EXIT

while true; do
  "\$CLAUDE_BIN" --dangerously-skip-permissions --profile orchestrator

  # Clean shutdown requested by daemon
  [ -f /tmp/orch-exit-requested ] && rm -f /tmp/orch-exit-requested && break

  # Context overflow restart
  if [ -f .claude/state/orch-restart-requested ]; then
    rm -f .claude/state/orch-restart-requested
    continue
  fi

  # Default: restart only if work remains
  PENDING=\$(curl -sf "http://localhost:\$DAEMON_PORT/api/orchestrator/tasks?status=pending,in_progress" \\
    | python3 -c "import sys,json; d=json.load(sys.stdin); print(len(d.get('data',[])))" 2>/dev/null || echo 0)
  [ "\$PENDING" -gt "0" ] && continue || break
done
`;
}

/**
 * Spawn an orchestrator tmux session running Claude Code.
 * Returns the session name, or null if spawn failed.
 *
 * The session runs a restart loop script that runs Claude with --profile orchestrator.
 * Claude discovers its tasks from the database (task queue) on each start.
 * The prompt parameter is accepted for backward compatibility but is not embedded
 * in the script — the orchestrator discovers tasks via the task queue.
 */
export function spawnOrchestratorSession(prompt: string): string | null {
  const session = resolveSession('orchestrator')!;

  // Check if already running
  try {
    execFileSync(TMUX_BIN, ['-S', TMUX_SOCKET, 'has-session', '-t', `=${session}`], {
      timeout: 5000,
    });
    log.info('Orchestrator session already exists — task is in queue, orch will pick it up', { session });
    return session;
  } catch {
    // Session doesn't exist — good, we'll create it
  }

  try {
    const restartScript = buildOrchestratorRestartLoop();

    // Write restart loop script to a temp file so tmux can execute it
    const scriptPath = `/tmp/kithkit-orch-${Date.now()}.sh`;
    writeFileSync(scriptPath, restartScript, { mode: 0o700 });

    // Create a new detached tmux session running the restart loop
    execFileSync(TMUX_BIN, [
      '-S', TMUX_SOCKET,
      'new-session',
      '-d',             // detached
      '-s', session,    // session name
      '-c', projectDir, // working directory
      '-x', '200',      // width
      '-y', '50',       // height
      '/bin/bash', scriptPath,
    ], {
      timeout: 10000,
      env: {
        ...process.env,
        PATH: `${process.env.HOME}/.local/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin`,
        CLAUDECODE: '',  // Clear nesting guard — orchestrator is a separate session
      },
    });

    log.info('Orchestrator session spawned with restart loop', { session, projectDir });
    return session;
  } catch (err) {
    log.error('Failed to spawn orchestrator session', {
      session,
      error: err instanceof Error ? err.message : String(err),
    });
    return null;
  }
}

// Keep for backward compatibility — exported so callers that imported it don't break at runtime.
// The new session model uses --profile orchestrator instead of a wrapper with -p <prompt>.
/** @deprecated Use the new restart loop model. This function is no longer called by spawnOrchestratorSession. */
export function buildOrchestratorWrapperScript(
  _claudeBin: string,
  _initialPrompt: string,
  _daemonPort: number = 3847,
): string {
  throw new Error('buildOrchestratorWrapperScript is deprecated — use buildOrchestratorRestartLoop (internal) instead');
}

/**
 * Kill the orchestrator tmux session.
 * Returns true if killed, false if session didn't exist.
 */
export function killOrchestratorSession(): boolean {
  const session = resolveSession('orchestrator')!;

  try {
    execFileSync(TMUX_BIN, ['-S', TMUX_SOCKET, 'kill-session', '-t', `=${session}`], {
      timeout: 5000,
    });
    log.info('Orchestrator session killed', { session });
    return true;
  } catch {
    log.warn('Orchestrator session not found for kill', { session });
    return false;
  }
}

/**
 * Check if the orchestrator session exists (alive = session running).
 * This returns true even when the wrapper is idle-waiting between tasks.
 */
export function isOrchestratorAlive(): boolean {
  const session = resolveSession('orchestrator')!;

  try {
    execFileSync(TMUX_BIN, ['-S', TMUX_SOCKET, 'has-session', '-t', `=${session}`], {
      timeout: 5000,
    });
    return true;
  } catch {
    return false;
  }
}

/**
 * Check if the orchestrator is actively running Claude (not just idle-waiting).
 *
 * The wrapper script runs Claude as a child of bash, so tmux's
 * pane_current_command always reports "bash". Instead, we grab the wrapper's
 * PID (#{pane_pid}) and use pgrep to check whether any "claude" process is a
 * descendant of that PID.
 *
 * Returns:
 *  - 'active'  — session exists and a claude process is running under the wrapper
 *  - 'waiting' — session exists but no claude child (idle polling loop)
 *  - 'dead'    — no session
 */
export function getOrchestratorState(): 'active' | 'waiting' | 'dead' {
  const session = resolveSession('orchestrator')!;

  try {
    execFileSync(TMUX_BIN, ['-S', TMUX_SOCKET, 'has-session', '-t', `=${session}`], {
      timeout: 5000,
    });
  } catch {
    return 'dead';
  }

  try {
    // Get the PID of the wrapper bash process that owns the tmux pane
    const panePid = execFileSync(TMUX_BIN, [
      '-S', TMUX_SOCKET,
      'display-message',
      '-t', `${session}:`,
      '-p', '#{pane_pid}',
    ], { timeout: 5000, encoding: 'utf8' }).trim();

    if (!panePid || !/^\d+$/.test(panePid)) {
      return 'waiting';
    }

    // Check if any "claude" process is a descendant of the wrapper PID
    try {
      execFileSync('/usr/bin/pgrep', ['-P', panePid, '-f', 'claude'], {
        timeout: 5000,
      });
      // pgrep exits 0 → at least one claude descendant found
      return 'active';
    } catch {
      // pgrep exits non-zero → no matching descendants
      return 'waiting';
    }
  } catch (err) {
    log.warn('getOrchestratorState: failed to determine process tree, assuming waiting', {
      error: err instanceof Error ? err.message : String(err),
    });
    return 'waiting';
  }
}

/**
 * List all tmux sessions managed by the daemon.
 */
export function listSessions(): string[] {
  try {
    const output = execFileSync(TMUX_BIN, [
      '-S', TMUX_SOCKET,
      'list-sessions',
      '-F', '#{session_name}',
    ], { timeout: 5000 }).toString().trim();
    return output ? output.split('\n') : [];
  } catch {
    return [];
  }
}

// ── Testing ─────────────────────────────────────────────────

export function _getCommsSession(): string { return COMMS_SESSION; }
export function _getOrchestratorSession(): string { return ORCH_SESSION; }
